### ISSUE TITLE
Have you considered using GitHub action to run it?

### ISSUE THREAD

**Issue by Caiiiiii** [4815162342lost/steam_gifts_bot#15]
Have you considered using GitHub action to run it? I try to run with Github action,but it always says that cookie is out of date.

**Comment by 4815162342lost** [comment]
I am not aware about GitHub action, but i think this is not save. Because steamgifts can ban your account due to "non-personal ip", i.e. GitHub IP. As far as i understand, do you want to run script on github servers instead of your PC?

Anyway, you should edit cookies before starting. Read wiki: https://github.com/4815162342lost/steam_gifts_bot/wiki#very-important-steps-before-installation

Id you want to add something else, please, reopen this topic. Always ready to discuss.
